name: Test

on:
  push:
    branches:
      - master

jobs:
  test-comment:
    runs-on: ubuntu-18.04
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v1
      - run: |
          echo ${{ github.event }}
